// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uyyxgihmyuajdxivjifj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5eXhnaWhteXVhamR4aXZqaWZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg5OTE3NDYsImV4cCI6MjA4NDU2Nzc0Nn0._uj5wHjkxF0uJpaPoGp6hw0AlsXOtirJOvJTi91a7dk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});