import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { MainLayout } from '@/components/layout/MainLayout';
import { useI18n } from '@/lib/i18n';
import { useAuth } from '@/hooks/useAuth';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { ArrowLeft, Save, Loader2 } from 'lucide-react';
import { toast } from 'sonner';

export default function NewPatient() {
  const { t, language } = useI18n();
  const { user, isDentist } = useAuth();
  const navigate = useNavigate();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [formData, setFormData] = useState({
    first_name: '',
    last_name: '',
    identity_number: '',
    phone: '',
    address: '',
    birth_date: '',
  });

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    setFormData(prev => ({
      ...prev,
      [e.target.name]: e.target.value,
    }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!formData.first_name.trim() || !formData.last_name.trim()) {
      toast.error(language === 'tr' ? 'Ad ve soyad zorunludur' : 'First name and last name are required');
      return;
    }

    if (!user) {
      toast.error(language === 'tr' ? 'Oturum açmanız gerekiyor' : 'You need to be logged in');
      return;
    }

    setIsSubmitting(true);

    try {
      const { data, error } = await supabase
        .from('patients')
        .insert({
          dentist_id: user.id,
          first_name: formData.first_name.trim(),
          last_name: formData.last_name.trim(),
          identity_number: formData.identity_number.trim() || null,
          phone: formData.phone.trim() || null,
          address: formData.address.trim() || null,
          birth_date: formData.birth_date || null,
          patient_ref: '', // Will be auto-generated by trigger
        })
        .select()
        .single();

      if (error) {
        console.error('Error creating patient:', error);
        toast.error(language === 'tr' ? 'Hasta kaydedilemedi' : 'Failed to save patient');
        return;
      }

      toast.success(language === 'tr' ? 'Hasta başarıyla kaydedildi' : 'Patient saved successfully');
      navigate(`/patients/${data.id}`);
    } catch (err) {
      console.error('Error:', err);
      toast.error(language === 'tr' ? 'Bir hata oluştu' : 'An error occurred');
    } finally {
      setIsSubmitting(false);
    }
  };

  if (!isDentist) {
    return (
      <MainLayout>
        <div className="container py-8 text-center">
          <p className="text-muted-foreground">
            {language === 'tr' ? 'Bu sayfaya erişim yetkiniz yok.' : 'You do not have access to this page.'}
          </p>
        </div>
      </MainLayout>
    );
  }

  return (
    <MainLayout>
      <div className="container py-8 max-w-2xl">
        <Button 
          variant="ghost" 
          onClick={() => navigate('/patients')}
          className="mb-6"
        >
          <ArrowLeft className="h-4 w-4 mr-2" />
          {t.common.back}
        </Button>

        <Card>
          <CardHeader>
            <CardTitle>{t.patients.addNew}</CardTitle>
          </CardHeader>
          <CardContent>
            <form onSubmit={handleSubmit} className="space-y-6">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="first_name">{t.patients.form.firstName} *</Label>
                  <Input
                    id="first_name"
                    name="first_name"
                    value={formData.first_name}
                    onChange={handleChange}
                    required
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="last_name">{t.patients.form.lastName} *</Label>
                  <Input
                    id="last_name"
                    name="last_name"
                    value={formData.last_name}
                    onChange={handleChange}
                    required
                  />
                </div>
              </div>

              <div className="space-y-2">
                <Label htmlFor="identity_number">{t.patients.form.identityNumber}</Label>
                <Input
                  id="identity_number"
                  name="identity_number"
                  value={formData.identity_number}
                  onChange={handleChange}
                />
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="phone">{t.patients.form.phone}</Label>
                  <Input
                    id="phone"
                    name="phone"
                    type="tel"
                    value={formData.phone}
                    onChange={handleChange}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="birth_date">{t.patients.form.birthDate}</Label>
                  <Input
                    id="birth_date"
                    name="birth_date"
                    type="date"
                    value={formData.birth_date}
                    onChange={handleChange}
                  />
                </div>
              </div>

              <div className="space-y-2">
                <Label htmlFor="address">{t.patients.form.address}</Label>
                <Textarea
                  id="address"
                  name="address"
                  value={formData.address}
                  onChange={handleChange}
                  rows={3}
                />
              </div>

              <div className="flex gap-4 pt-4">
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => navigate('/patients')}
                  disabled={isSubmitting}
                >
                  {t.patients.form.cancel}
                </Button>
                <Button type="submit" disabled={isSubmitting} className="gradient-primary">
                  {isSubmitting ? (
                    <>
                      <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                      {language === 'tr' ? 'Kaydediliyor...' : 'Saving...'}
                    </>
                  ) : (
                    <>
                      <Save className="h-4 w-4 mr-2" />
                      {t.patients.form.save}
                    </>
                  )}
                </Button>
              </div>
            </form>
          </CardContent>
        </Card>
      </div>
    </MainLayout>
  );
}
