import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useI18n } from '@/lib/i18n';
import { useAuth } from '@/hooks/useAuth';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Loader2, UserPlus } from 'lucide-react';

interface QuickAddPatientDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSuccess?: () => void;
}

export function QuickAddPatientDialog({ open, onOpenChange, onSuccess }: QuickAddPatientDialogProps) {
  const { t, language } = useI18n();
  const { user } = useAuth();
  const { toast } = useToast();
  const navigate = useNavigate();
  
  const [firstName, setFirstName] = useState('');
  const [lastName, setLastName] = useState('');
  const [phone, setPhone] = useState('');
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!user) return;
    if (!firstName.trim() || !lastName.trim()) {
      toast({
        title: language === 'tr' ? 'Hata' : 'Error',
        description: language === 'tr' ? 'Ad ve soyad zorunludur' : 'First name and last name are required',
        variant: 'destructive',
      });
      return;
    }

    setLoading(true);

    try {
      const { data, error } = await supabase
        .from('patients')
        .insert([{
          dentist_id: user.id,
          first_name: firstName.trim(),
          last_name: lastName.trim(),
          phone: phone.trim() || null,
          patient_ref: '', // Will be auto-generated by trigger
        }])
        .select()
        .single();

      if (error) throw error;

      toast({
        title: language === 'tr' ? 'Başarılı' : 'Success',
        description: language === 'tr' ? 'Hasta başarıyla eklendi' : 'Patient added successfully',
      });

      // Reset form
      setFirstName('');
      setLastName('');
      setPhone('');
      onOpenChange(false);
      
      if (onSuccess) {
        onSuccess();
      }

      // Navigate to patient detail
      if (data?.id) {
        navigate(`/patients/${data.id}`);
      }
    } catch (error: any) {
      console.error('Error adding patient:', error);
      toast({
        title: language === 'tr' ? 'Hata' : 'Error',
        description: error.message || (language === 'tr' ? 'Hasta eklenirken hata oluştu' : 'Error adding patient'),
        variant: 'destructive',
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <UserPlus className="h-5 w-5" />
            {t.dashboard.addPatient}
          </DialogTitle>
          <DialogDescription>
            {language === 'tr' 
              ? 'Hızlıca yeni bir hasta ekleyin. Detaylı bilgileri daha sonra düzenleyebilirsiniz.'
              : 'Quickly add a new patient. You can edit detailed information later.'}
          </DialogDescription>
        </DialogHeader>
        
        <form onSubmit={handleSubmit}>
          <div className="grid gap-4 py-4">
            <div className="grid gap-2">
              <Label htmlFor="firstName">{t.patients.form.firstName} *</Label>
              <Input
                id="firstName"
                value={firstName}
                onChange={(e) => setFirstName(e.target.value)}
                placeholder={language === 'tr' ? 'Hastanın adı' : "Patient's first name"}
                disabled={loading}
                autoFocus
              />
            </div>
            
            <div className="grid gap-2">
              <Label htmlFor="lastName">{t.patients.form.lastName} *</Label>
              <Input
                id="lastName"
                value={lastName}
                onChange={(e) => setLastName(e.target.value)}
                placeholder={language === 'tr' ? 'Hastanın soyadı' : "Patient's last name"}
                disabled={loading}
              />
            </div>
            
            <div className="grid gap-2">
              <Label htmlFor="phone">{t.patients.form.phone}</Label>
              <Input
                id="phone"
                type="tel"
                value={phone}
                onChange={(e) => setPhone(e.target.value)}
                placeholder={language === 'tr' ? 'Telefon numarası (isteğe bağlı)' : 'Phone number (optional)'}
                disabled={loading}
              />
            </div>
          </div>
          
          <DialogFooter>
            <Button 
              type="button" 
              variant="outline" 
              onClick={() => onOpenChange(false)}
              disabled={loading}
            >
              {language === 'tr' ? 'İptal' : 'Cancel'}
            </Button>
            <Button type="submit" disabled={loading}>
              {loading && <Loader2 className="h-4 w-4 mr-2 animate-spin" />}
              {t.dashboard.addPatient}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
